name: ubuntu
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_INCLUDE-HIDDEN-FILES: true
      INPUT_NAME: files
      INPUT_OVERWRITE: true
    steps:
    # - run: |
    #     echo $PATH && \
    #     cd /usr/local/bin && \
    #     sudo curl https://github.com/dirkarnez/transfersh/releases/download/v1.0.0/transfersh-v1.0.0-ubuntu-latest.zip -L -O -J && \
    #     sudo unzip transfersh-v1.0.0-ubuntu-latest.zip && \
    #     sudo ls -R

    - uses: actions/checkout@v4
      with:
        repository: actions/upload-artifact
        ref: v4.5.0
        path: upload-artifact
        submodules: true

    - working-directory: upload-artifact
      run: npm i
        
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
#     - uses: actions/checkout@v2
#     - run: source script-linux.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
