name: ubuntu
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $PATH && \
        cd /usr/local/bin && \
        sudo curl https://github.com/dirkarnez/transfersh/releases/download/v1.0.0/transfersh-v1.0.0-ubuntu-latest.zip -L -O -J && \
        sudo unzip transfersh-v1.0.0-ubuntu-latest.zip && \
        sudo ls -R
        
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
#     - uses: actions/checkout@v2
#     - run: source script-linux.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
